#!/usr/bin/env ruby
# frozen_string_literal: true

require "rack"
require "anycable"
require "litecable"
require_relative './config/boot'

LiteCable.anycable!


Anycable.connection_factory = Web::Connection
# Anycable.configure do |config|
#   puts "ANY CONNECTION: #{config.connection_factory}"
#   config.connection_factory = Web::Connection
# end

Anycable::Server.start
